### ISSUE TITLE
MicrosoftTeams v2.5.0 or higher has nested Objects for Policies

### ISSUE THREAD

**Issue by DEberhardt** [DEberhardt/TeamsFunctions#123]
Policy Names do currently not return the correct Name when called with `$CsUser.OnlineVoiceRoutingPolicy` as the OVP here is a nested Object. This seems to be a bug.

## Workaround
```powershell
#Replicate for all calls to OVPs, TDPs, etc:
$OVPName = if ( $UserObject.OnlineVoiceRoutingPolicy.Name ) { $UserObject.OnlineVoiceRoutingPolicy.Name } else { $UserObject.OnlineVoiceRoutingPolicy }
```

To be evaluated/tested

**Comment by DEberhardt** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/issues/8960

**Comment by poshdude** [comment]
Just cast it as a string and you should have parity.  The newer API version of the MicrosoftTeams returns a Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.UserPolicyDefinition object instead of System.String as previously...

```
$OVPName = [string] $UserObject.OnlineVoiceRoutingPolicy
```

**Comment by DEberhardt** [comment]
that it way more elegant than my little IF - thank you, will add it once I get to reworking these

**Comment by DEberhardt** [comment]
Working as intended - only used once in the code, so closing this here.
