### ISSUE TITLE
Get-TeamsCallQueue returns no error when Basic authentication is disabled

### ISSUE THREAD

**Issue by mwilens** [DEberhardt/TeamsFunctions#126]
Get-TeamsCallQueue -SearchString CQ-Name returns nothing at all while Get-CsCallQueue returns the error WinRM client cannot process the request, Basic authentication is currently disabled in the client configuration.
Found this by accident because the policy resets this registry key of my workstation every day

**Comment by DEberhardt** [comment]
oh? How are you connected to MicrosoftTeams btw? - If you don't get a "you are not connected"-message, the output issue may lie in the treatment of errors...

I have just reworked `Get-TeamsCallQueue` to support paging (more here: #94 )
If you could give me a sanitised verbose output, I could maybe glean what is happening, but I think I simply swallow the errors here.
