### ISSUE TITLE
Get-TeamsCallQueue -Name "Call Queue Name" error

### ISSUE THREAD

**Issue by mbauer7072** [DEberhardt/TeamsFunctions#22]
getting this error when attempting to search for a specific call queue name:

PS C:\windows\system32> Get-TeamsCallQueue -Name "OSFA Ombuds" -Verbose
VERBOSE: INFO:  Session found, reusing existing connection to AzureAD - Tenant: Removed for Security Reasons
VERBOSE: INFO:  Session found, reusing existing connection to SkypeOnline
VERBOSE: All Parameters except 'LineUri' are shown
VERBOSE: 'OSFA Ombuds' OverflowActionTarget: Not configured
VERBOSE: 'OSFA Ombuds' TimeoutActionTarget: Not configured
VERBOSE: 'OSFA Ombuds' Parsing DistributionLists
VERBOSE: 'OSFA Ombuds' Parsing Users
Get-TeamsCallQueue : Could not query Call Queues
At line:1 char:1
+ Get-TeamsCallQueue -Name "OSFA Ombuds" -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-TeamsCallQueue

Exception : Cannot bind argument to parameter 'ObjectId' because it is null.
Reason    : ParameterBindingValidationException
Target    :
Script    : C:\Program Files\WindowsPowerShell\Modules\TeamsFunctions\20.8\TeamsFunctions.psm1
Line      : 3988
Column    : 53

**Comment by DEberhardt** [comment]
Hello,

Thank you for your feedback.
I have found and fixed the issue in the Prerealease version.
20.09 will be published soon if you want to wait:)

Best regards,
David

Apologies for the brief nature of this email as it has been sent from my phone.
________________________________

**Comment by mbauer7072** [comment]
David,

I appreciate the quick turnaround and I will wait. I do appreciate all of the hard work you have done to make life easier for us Teams Admins 😊

Best Regards,

Mike Bauer

**Comment by DEberhardt** [comment]
Hello again,

I just released v20.09 on PowerShellGet. If you update now, you should be able to run it without issues. :)
My apologies, had a nasty typo in it that shouldn't have been there.

best regards,
David
