### ISSUE TITLE
set-teamsuservoiceconfig  failing because parameter 'UserObject' is specified more than once. 

### ISSUE THREAD

**Issue by pierok13** [DEberhardt/TeamsFunctions#97]
Hey,
great work you did, escpecially with the new PS 2.5.1 !!!
When trying to enable a user for direct routing, I get an error 

> EnableEV : Cannot bind parameter because parameter 'UserObject' is specified more than once. To provide multiple values to >parameters that can accept multiple values, use the array 
>syntax. For example, "-parameter value1,value2,value3".
>At
 >WindowsPowerShell\Modules\TeamsFunctions\21.9\Public\Functions\Support\VoiceConfig\Enable-TeamsUserForEnterpriseVoice.ps1:212 char:66
> EnableEV -UserObject $CsUser -UserLicense $UserLicense @Parameters
>\+                                                               ~~~~~~~~~~~
>    \+ CategoryInfo          : InvalidArgument: (:) [EnableEV], ParameterBindingException
>    \+ FullyQualifiedErrorId : ParameterAlreadyBound,EnableEV
 

From the source code I see that obvisously we are calling the enableEv with -object and @parameters that also includes userobject

**Comment by DEberhardt** [comment]
Hello & thank you :smile:
I recently refactored this one to hand the object over rather than querying it again.
Seems I have missed something here...

```powershell
          EnableEV @Parameters
          EnableEV -UserObject $CsUser -UserLicense $UserLicense @Parameters
```
Well, seems I stopped writing half-way through. Oops.

Will push an update out in a sec, this is too embarrassing to leave in^^

**Comment by DEberhardt** [comment]
21.9.2 is out :)
